### ISSUE TITLE
Exercise solutions?

### ISSUE THREAD

**Issue by kubukoz** [isovector/algebra-driven-design#8]
Hi! First of all, thanks for writing the book, I'm a proud owner and I'm currently going through it :)

I was wondering if there's anywhere I can find answers to the exercises from the book - want to make sure I got them right, and I didn't find anything in the book itself.

**Comment by isovector** [comment]
Hi @kubukoz! Thanks for getting in touch!

The answers to exercises, if they exist, are already in the book, immediately after the exercises. But I'm happy to check any solutions you might be curious about!

**Comment by kubukoz** [comment]
Thanks for the reply!

The last time I saw a "Solution" (capital S) was at the very end of chapter 2.1 🤔 I'm in 4.5 now.

I'm thinking of these, for example:

```
// Chapter 4.3
Exercise Give a law for the behavior of shorterOf.
//
Does shorterOf form a monoid? If so, give it. If not, show which laws it doesn’t satisfy.
```

For the former, I have a couple laws (e.g. concat, commutativity, associativity). For the latter, I concluded that it doesn't have an identity element. I'm _pretty sure_ this is right, but I did not find 

And then there's this one from a couple pages back:

```
Exercise Give semantics for andThen in terms of

completes :: Challenge -> [Input] -> Bool.

Show that your these semantics necessarily contradict "andThen/gate".
```

The text below explains the idea of contradictions and what to do when you spot them, but doesn't say why they occur in this case.

I tried to give the following semantics (Scala):

```scala
def completes(
  c: Challenge,
  is: List[Input],
): Boolean

def `complete/andThen`(
  c1: Challenge,
  c2: Challenge,
  is1: List[Input],
  is2: List[Input],
) =
  completes(andThen(c1, c2), is1 ++ is2) ==
    completes(c1, is1) && completes(c2, is2)
```


 I have a pseudo-proof:

```scala
// A
completes(andThen(c1, c2), is1 ++ is2) ==
  completes(c1, is1) && completes(c2, is2)

// B
andThen(gate(f, c1), c2) == gate(f, andThen(c1, c2))

// Challenge: prove A contradicts B
// the idea: substitute things within A until the equation is falsified
// in A, substitute all `c1`s with gate(f,c1)
completes(andThen(gate(f, c1), c2), is1 ++ is2) ==
  completes(gate(f, c1), is1) && completes(c2, is2)

// substitute andThen(gate(f, c1), c2) == gate(f, andThen(c1, c2)), via B
completes(gate(f, andThen(c1, c2)), is1 ++ is2) ==
  completes(gate(f, c1), is1) && completes(c2, is2)

// at this point I just have prose:
// if is1 doesn't complete c1 BUT (is1 ++ is2) completes both c1 and c2, LHS may be true but RHS will be false
// e.g. is1=Nil and is2 is the concatenation of both
// is that sufficient proof? Is there a cleaner version to get here?
```

for the record, I'm on version 1.1.3 (seems like the latest), both the PDF and the .mobi version seem to be missing answers past 2.1.

**Comment by isovector** [comment]
> For the latter, I concluded that it doesn't have an identity element.

Right!

> I have a pseudo-proof

TBH I don't recall what I had in mind for this exercise, but your proof looks convincing to me. After substitution, you're still completing `c2` even though you shouldn't be allowed to! 

More generally, you can show this as an argument about confluence --- every path you can take while rewriting an expression should end up in the same place. A series of laws which don't satisfy confluence necessarily have a contradiction somewhere.

**Comment by kubukoz** [comment]
Thanks :)

I'll close for now, but personally I'd appreciate more solutions in the book to compare mine against - but no pressure, just treat me as a datapoint if you consider adding some ;)
